# Generated by Django 4.2 on 2023-05-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='study_field',
        ),
    ]
